"""Add purchase condition to assets

Revision ID: 4e3890d10f9b
Revises: 1dec6a0ee73a
Create Date: 2026-06-20 17:38:25.630576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3890d10f9b'
down_revision = '1dec6a0ee73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_condition', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('purchase_condition')

    # ### end Alembic commands ###
