"""Add code prefix to categories

Revision ID: 60f1e276486a
Revises: 9d69dad0ad4b
Create Date: 2026-07-02 18:39:21.468127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f1e276486a'
down_revision = '9d69dad0ad4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_prefix', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('code_prefix')

    # ### end Alembic commands ###
